data_folder: "/datasets/sai/scenes_merged"
pretrained_model_name_or_path: "/datasets/sai/focal-burst-learning/svd/svdh"
load_from_checkpoint: "/datasets/sai/focal-burst-learning/svd/training/outputs/final_checkpoint"
output_dir: "/datasets/sai/focal-burst-learning/svd/outputs"
wandb_project: "RefocusingSVD"
test: true
revision: null
num_frames: 9
num_validation_images: 1
validation_steps: 1000
photos: false
conditioning: "random"
seed: 0
per_gpu_batch_size: 1
num_train_epochs: 600
max_train_steps: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 0.00001
reconstruction_guidance: 0
scale_lr: true
lr_scheduler: "constant"
lr_warmup_steps: 0
conditioning_dropout_prob: 0.1
use_8bit_adam: false
allow_tf32: false
use_ema: false
non_ema_revision: null
num_workers: 32
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 0.0000001
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: "logs"
mixed_precision: null
report_to: "wandb"
local_rank: -1
checkpointing_steps: 500
checkpoints_total_limit: 2
enable_xformers_memory_efficient_attention: false
pretrain_unet: null
